version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
        exclude-patterns:
          - "org.jetbrains.kotlin*"
    schedule:
      interval: weekly
      day: "monday"
      time: "01:32"
      timezone: "Europe/Oslo"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"
      time: "01:32"
      timezone: "Europe/Oslo"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"
      time: "01:32"
      timezone: "Europe/Oslo"

  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: weekly
      day: "monday"
      time: "01:32"
      timezone: "Europe/Oslo"
