version: "3.9"
services:
  database:
    container_name: nibas-events-db
    image: postgis/postgis
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=nibas
      - POSTGRES_PASSWORD=nibas
      - TZ=Europe/Oslo
      - PGTZ=Europe/Oslo
volumes:
  db_volume: {}

