management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: 'info, health, prometheus'
    jmx:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true
    info:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
      show-details: always
    metrics:
      enabled: true
    env:
      enabled: true
  info:
    env:
      enabled: true
  health:
    vault:
      enabled: false

info:
  application:
    version: ${PROJECT_VERSION}

springdoc:
  api-docs:
    path: /api-docs

spring:
  application:
    name: nibas-events

  main:
    banner-mode: "OFF"

  jmx:
    enabled: true

  profiles:
    group:
      localhost:
        - "humanReadableLog"

  jackson:
    time-zone: "Europe/Oslo"

  flyway:
    schemas: nibas

---
spring:
  config:
    activate:
      on-profile: localhost
  datasource:
    url: ${DB_CONNECTION_STRING:jdbc:postgresql://localhost:5433/nibas}
    username: ${DB_USER:nibas}
    password: ${DB_PASSWORD:nibas}
