management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: 'info, health'
    jmx:
      exposure:
        include: '*'
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true
    env:
      enabled: true
  info:
    env:
      enabled: true

info:
  application:
    version: ${PROJECT_VERSION}

springdoc:
  api-docs:
    path: /api-docs

spring:
  application:
    name: nibas-events

  main:
    banner-mode: "OFF"

  jmx:
    enabled: true

  profiles:
    group:
      localhost:
        - "humanReadableLog"

  jackson:
    time-zone: "Europe/Oslo"

  cloud:
    vault:
      uri: https://vault.vault:8200
      authentication: kubernetes
      kubernetes:
        role: nibas # Er en rolle definert hos skip
        kubernetes-path: ${KUBERNETES_CLUSTER}
        service-account-token-file: /var/run/secrets/kubernetes.io/serviceaccount/token
      ssl:
        trust-store: classpath:ca.jks
        trust-store-type: jks
        trust-store-password: changeit
      connection-timeout: 5000
      read-timeout: 15000
    gcp:
      project-id: ${GOOGLE_CLOUD_PROJECT}
      pubsub:
        enabled: true
      core:
        enabled: true

  config:
    import: optional:vault://nibas/nibas-events-apikeys, optional:vault://nibas/nibas-events-db

  flyway:
    schemas: nibas

nibas:
  pubsub:
    subscription: nibas-events-subscriber

---
spring:
  config:
    activate:
      on-profile: localhost
  datasource:
    url: ${DB_CONNECTION_STRING:jdbc:postgresql://localhost:5433/nibas}
    username: ${DB_USER:nibas}
    password: ${DB_PASSWORD:nibas}
  cloud:
    vault:
      uri: ${VAULT_ADDR:https://vault.dev.skip.statkart.no/}
      authentication: token
      token: ${VAULT_TOKEN}
      enabled: true
    gcp:
      pubsub:
        enabled: false
      core:
        enabled: false

