management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: '*'
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  info:
    env:
      enabled: true

info:
  application:
    version: ${PROJECT_VERSION}

springdoc:
  api-docs:
    path: /api-docs

spring:
  application:
    name: nibas-events

  jackson:
    time-zone: "Europe/Oslo"

  cloud:
    vault:
      ssl:
        trust-store: classpath:ca.jks
        trust-store-type: jks
        trust-store-password: changeit
      connection-timeout: 5000
      read-timeout: 15000
  config:
    import: vault://nibas/nibas-events-db

  flyway:
    schemas: nibas
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}

  kafka:
    bootstrap-servers: nibas-kafka:9092
    consumer:
      properties:
        spring:
          json:
            value:
              default:
                type: no.kartverket.nibas.api.v1.request.EventRequest
            trusted:
              packages: no.kartverket.nibas.events.EventRequest.v1.request
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: nibas-events
      auto-offset-reset: earliest


---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    vault:
      uri: https://vault.dev.skip.statkart.no/
      authentication: kubernetes
      kubernetes:
        role: nibas # Er en rolle definert hos skip
        kubernetes-path: atkv1-dev
        service-account-token-file: /var/run/secrets/kubernetes.io/serviceaccount/token
---
spring:
  config:
    activate:
      on-profile: localhost
    import: vault://nibas/nibas-events-db-local
  cloud:
    vault:
      uri: https://vault.dev.skip.statkart.no/
      authentication: token
      token: ${VAULT_TOKEN}
      enabled: true
  kafka:
    bootstrap-servers: localhost:29092
nibas:
  kafka:
    autoStartup: false
