[versions]
flywayVersion = "12.0.3"
kotlinMockitoVersion = "6.2.3"
kotlinPluginVersion = "2.2.21"
logstashVersion = "9.0"
prometheusVersion = "1.16.3"
springDependencyManagementVersion = "1.1.7"
springFrameworkVersion = "4.0.1"
springdocOpenapiVersion2 = "3.0.1"
testContainerVersion = "1.21.4"

[libraries]
flyway-postgres = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flywayVersion" }
spring-flyway = { module = "org.springframework.boot:spring-boot-starter-flyway" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }
kotlin-mockito = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "kotlinMockitoVersion" }
kotlin-stdlib-jdk = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8" }
logstash-logback-encoder = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logstashVersion" }
micrometer-registry-prometheus = { module = "io.micrometer:micrometer-registry-prometheus", version.ref = "prometheusVersion" }
postgres = { module = "org.postgresql:postgresql" }
spring-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-jdbc = { module = "org.springframework.boot:spring-boot-starter-data-jdbc" }
spring-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-validator = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
spring-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }
springdoc-openapi-common = { module = "org.springdoc:springdoc-openapi-starter-common", version.ref = "springdocOpenapiVersion2" }
springdoc-openapi-webmvc-api = { module = "org.springdoc:springdoc-openapi-starter-webmvc-api", version.ref = "springdocOpenapiVersion2" }
springdoc-openapi-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdocOpenapiVersion2" }
testcontainers-junit = { module = "org.testcontainers:junit-jupiter", version.ref = "testContainerVersion" }
testcontainers-postgres = { module = "org.testcontainers:postgresql", version.ref = "testContainerVersion" }

[plugins]
flyway = { id = "org.flywaydb.flyway", version.ref = "flywayVersion" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagementVersion" }
spring-framework = { id = "org.springframework.boot", version.ref = "springFrameworkVersion" }
