name: nibas-feature-branches

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set local timezone
        run: sudo timedatectl set-timezone "Europe/Oslo"
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --info

