name: nibas-master
on:
  push:
    branches: [ master ]

permissions:
  id-token: write
  contents: 'read'

env:
  image_name: nibas-events
  registry: ghcr.io
  registry_path: kartverket

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      security-events: write
      actions: read

    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}

    steps:
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/Oslo"
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --info

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ github.token }}

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password:  ${{ github.token }}

      - name: Build docker and push
        id: build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ github.repository }}:${{ steps.tag_version.outputs.new_tag }}
          build-args: | 
            project_version_arg=${{ steps.tag_version.outputs.new_tag }}

      - name: Run Trivy vulnerability scanner
        id: securityscan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ steps.build.outputs.full_image_name }}:${{ steps.tag_version.outputs.new_tag }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'

  deploy:
    needs: build
    runs-on: ${{ matrix.environment }}
    environment: ${{ matrix.environment }}
    strategy:
      matrix:
        environment: [ 'atkv1-dev' ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Fetch environment variables and set for subsequent steps
    - name: read .env
      uses: c-py/action-dotenv-to-setenv@v3
      with: 
        env-file: .github/workflows/.env.${{matrix.environment}}
      
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Get JWT
      id: githubtoken
      uses: magic7s/expose-jwt-action@v0.1.1

    - run: |
        echo "TF_VAR_GITHUB_TOKEN=${{ steps.githubtoken.outputs.jwt }}" >> $GITHUB_ENV
      

    # Authenticate with google cloud serviceaccount to have permissions in cluster.
    # Variabel project_id må settes til kubernetesprosjektet her.   
    - id: auth
      name: Authenticate to GCP
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: ${{env.WORKLOAD_IDENTITY_FEDERATION_PROVIDER}}
        service_account: ${{env.WORKLOAD_IDENTITY_FEDERATION_SERVICE_ACCOUNT}}
        project_id: ${{env.TF_VAR_PROJECT_ID}}

    - name: Authenticate with cluster
      run: gcloud container hub memberships get-credentials ${{ matrix.environment }} --verbosity debug
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false

    - name: Generate terraform variables
      run: |
        cat <<EOF >> ${{ env.TF_ROOT }}/terraform.tfvars
        vault_addr="${{ env.VAULT_ADDR }}"
        vault_skip_verify="${{ env.VAULT_SKIP_VERIFY }}"
        nibas_events_version="${{ needs.build.outputs.new_tag }}"
        EOF
    
    - name: Generate terraform backend variables
      run: |
        cat <<EOF >> ${{ env.TF_ROOT }}/backend.tfbackend
        bucket="${{ env.BUCKET }}"
        EOF
    
    - name: Terraform init
      run: terraform init -input=false -backend-config=backend.tfbackend
      working-directory: ${{ env.TF_ROOT }}

    - name: Terraform plan
      run: terraform plan -input=false
      working-directory: ${{ env.TF_ROOT }}

    - name: Terraform apply
      run: terraform apply -input=false -auto-approve
      working-directory: ${{ env.TF_ROOT }}
