name: nibas-master
on:
  push:
    branches: [ master ]

permissions:
  id-token: write
  contents: 'read'

env:
  image_name: nibas-events
  registry: ghcr.io
  registry_path: kartverket

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      security-events: write
      actions: read

    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
      image_url: ${{ steps.setOutput.outputs.image_url }}

    steps:
      - uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: "Europe/Oslo"
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --info

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ github.token }}

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password:  ${{ github.token }}

      - name: Build docker and push
        id: build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.registry }}/${{ github.repository }}:${{ steps.tag_version.outputs.new_tag }}
          build-args: | 
            project_version_arg=${{ steps.tag_version.outputs.new_tag }}

      - name: Set output with build values
        id: setOutput
        run: |
            echo "image_url=${{ env.registry }}/${{ github.repository }}@${{ steps.build.outputs.digest }}" >> $GITHUB_OUTPUT

  set-variables:
    runs-on: ubuntu-latest
    outputs:
      dev_auth_project_number: ${{ steps.set-dev-variables.outputs.dev_auth_project_number }}
      dev_service_account: ${{ steps.set-dev-variables.outputs.dev_service_account }}
    steps:
      - name: Set dev variables
        id: set-dev-variables
        run: |
          echo "dev_auth_project_number=747318126147" >> $GITHUB_OUTPUT
          echo "dev_service_account=nibas-deploy@nibas-dev-075c.iam.gserviceaccount.com" >> $GITHUB_OUTPUT

  post-build-attest:
    needs: [build, set-variables]
    name: Authentication and Attestation of Build
    permissions:
      contents: read
      packages: write
      id-token: write
      actions: read
      security-events: write
      statuses: write
    uses: kartverket/github-workflows/.github/workflows/post-build-attest.yml@v3.0.3
    with:
      auth_project_number: ${{ needs.set-variables.outputs.dev_auth_project_number}}
      service_account: ${{ needs.set-variables.outputs.dev_service_account}}
      image_url: ${{ needs.build.outputs.image_url}} # the image created by build job

  deploy-dev:
    needs: [build, set-variables]
    permissions:
      id-token: write
      pull-requests: write
      contents: read
      packages: write
    uses: kartverket/github-workflows/.github/workflows/run-terraform.yml@v3.1.0
    with:
      runner: atkv1-dev
      environment: dev
      kubernetes_cluster: atkv1-dev
      terraform_workspace: dev
      terraform_option_1: -var-file=variables/dev.tfvars
      terraform_option_2: -var=NIBAS_EVENTS_VERSION=${{ needs.build.outputs.new_tag }}
      terraform_init_option_1: -backend-config=backend/dev.gcs.tfbackend
      working_directory: terraform
      auth_project_number: ${{ needs.set-variables.outputs.dev_auth_project_number}}
      service_account: ${{ needs.set-variables.outputs.dev_service_account}}
      vault_role: nibas-events-write-role
      project_id: kubernetes-dev-94b9
      deploy_on: 'refs/heads/master'

  security-scans:
    needs: [ build, set-variables ]
    name: Security Scans
    permissions:
      contents: read
      packages: write
      id-token: write
      actions: read
      security-events: write
    uses: kartverket/github-workflows/.github/workflows/run-security-scans.yml@v3.0.3
    with:
      auth_project_number: ${{ needs.set-variables.outputs.dev_auth_project_number}}
      service_account: ${{ needs.set-variables.outputs.dev_service_account}}
      image_url: ${{ needs.build.outputs.image_url}}

  deploy-test:
    needs: [build, security-scans]
    permissions:
      id-token: write
      pull-requests: write
      contents: read
      packages: write
    uses: kartverket/github-workflows/.github/workflows/run-terraform.yml@v3.1.0
    with:
      runner: atkv1-test
      environment: test
      kubernetes_cluster: atkv1-test
      terraform_workspace: test
      terraform_option_1: -var-file=variables/test.tfvars
      terraform_option_2: -var=NIBAS_EVENTS_VERSION=${{ needs.build.outputs.new_tag }}
      terraform_init_option_1: -backend-config=backend/test.gcs.tfbackend
      working_directory: terraform
      service_account: nibas-deploy@nibas-test-36cb.iam.gserviceaccount.com
      auth_project_number: 935702487708
      vault_role: nibas-events-write-role
      project_id: kubernetes-test-94f6
      deploy_on: 'refs/heads/master'

  deploy-prod:
    needs: [ build, post-build-attest, security-scans, deploy-test ]
    permissions:
      id-token: write
      pull-requests: write
      contents: read
      packages: write
    uses: kartverket/github-workflows/.github/workflows/run-terraform.yml@v3.1.0
    with:
      runner: atkv1-prod
      environment: prod
      kubernetes_cluster: atkv1-prod
      terraform_workspace: prod
      terraform_option_1: -var-file=variables/prod.tfvars
      terraform_option_2: -var=NIBAS_EVENTS_VERSION=${{ needs.build.outputs.new_tag }}
      terraform_init_option_1: -backend-config=backend/prod.gcs.tfbackend
      working_directory: terraform
      service_account: nibas-deploy@nibas-prod-732a.iam.gserviceaccount.com
      auth_project_number: 468770754406
      vault_role: nibas-events-write-role
      project_id: kubernetes-prod-e4a2
      deploy_on: 'refs/heads/master'
